export { default as Home } from "./Home";
export { default as Jobs } from "./Jobs";
export { default as Map } from "./Map";
export { default as History } from "./History";
export { default as Tracking } from "./Tracking";
export { default as NotFound } from "./NotFound";
export { default as TruckManagement } from "./TruckManagement";
export { default as DriverManagement } from "./DriverManagement";
// export { default as CustomerManagement } from "./CustomerManagement";
// export { default as DeviceManagement } from "./DeviceManagement";
// export { default as DriverCompanyManagement } from "./DriverCompanyManagement";
// export { default as FleetManagement } from "./FleetManagement";
// export { default as FleetCarrierManagement } from "./FleetCarrierManagement";
// export { default as CarrierManagement } from "./CarrierManagement";
// export { default as CompanyManagement } from "./CompanyManagement";
// export { default as SalesOrderManagement } from "./SalesOrderManagement";
// export { default as ChargeFeeManagement } from "./ChargeFeeManagement";
export { default as PermissionDenied } from "./PermissionDenied";
export { default as RoutingSample } from "./RoutingSample";
export { default as Dashboard } from "./Dashboard";
export { default as Profile } from "./Profile";
export { default as TrackingOrder } from "./TrackingOrder";
export { default as RatingManagement } from "./RatingManagement";
export { default as Report } from "./Report";

