export { default as Toggle } from "./Toggle";
export { default as DropdownLanguage } from "./DropdownLanguage";
export { default as Navbar } from "./Navbar";
export { default as Breadcrumbs } from "./Breadcrumbs";
export { default as LoginUsername } from "./Login/LoginUsername";
export { default as LoginPassword } from "./Login/LoginPassword";
// export { default as TermsOfUse } from "./TermsOfUse";
// export { default as ListVehicles } from "./ListVehicles";
export { default as Sidebar } from "./Sidebar";
export { default as ListJob } from "./Job/ListJob";
export { default as ListTruck } from "./Job/ListTruck";
export { default as Feeds } from "./Job/Feeds";
export { default as JobDetail } from "./Job/JobDetail";
// export { default as AddDriver } from "./Driver/AddDriver";
// export { default as DeleteDriver } from "./Driver/DeleteDriver";
// export { default as AddFleet } from "./Fleet/AddFleet";
export { default as AddTruck } from "./Truck/AddTruck";
export { default as AddCustomer } from "./Customer/AddCustomer";
// export { default as AddDevice } from "./Device/AddDevice";
// export { default as AddChargeFee } from "./ChargeFee/AddChargeFee";
// export { default as AddSalesOrder } from "./SalesOrder/AddSalesOrder";
export { default as DeleteTruck } from "./Truck/DeleteTruck";
export { default as DeleteCustomer } from "./Customer/DeleteCustomer";
// export { default as DeleteDevice } from "./Device/DeleteDevice";
// export { default as DeleteArea } from "./Area/DeleteArea";
// export { default as EditArea } from "./Area/EditArea";
// export { default as EditAreaDrivers } from "./Area/EditAreaDrivers";
// export { default as DeleteChargeFee } from "./ChargeFee/DeleteChargeFee";
// export { default as DeleteSalesOrder } from "./SalesOrder/DeleteSalesOrder";
// export { default as AddCarrier } from "./Carrier/AddCarrier";
// export { default as AssignJob } from "./Job/AssignJob";
// export { default as AssignFleet } from "./Carrier/AssignFleet";
export { default as AssignDriverToTruck } from "./Truck/AssignDriverToTruck";
// export { default as AssignTruckToDriver } from "./Driver/AssignTruckToDriver";
// export { default as AssignCarrier } from "./Fleet/AssignCarrier";
export { default as MenuActions } from "./Job/MenuActions";
export { default as Calendar } from "./Job/Calendar/Calendar";
export { default as CustomAsyncSelect } from "./FormField/CustomAsyncSelect";
export { default as Map } from "./Tracking/Map";
export { default as TrucksAndDrivers } from "./Tracking/TrucksAndDrivers";
export { default as SpeedDialTracking } from "./Tracking/SpeedDialTracking";
export { default as Footer } from './Footer';
// export { default as AddArea } from './Area/AddArea';
export { default as ImportCustomerFromExcel } from './Customer/ImportCustomerFromExcel';
export { default as DeleteIDSender } from './IDSender/DeleteIDSender';
export { default as DeleteIDDeliveryShipTo } from './IDDeliveryShipTo/DeleteIDDeliveryShipTo';
export { default as DeleteUnit } from './Unit/DeleteUnit';
export { default as DeleteCaculationOrder } from './CaculationOrder/DeleteCaculationOrder';
export { default as DeleteStaff } from './RttStaff/DeleteStaff';
export { default as DeleteDocumentType } from './DocumentType/DeleteDocumentType';


